#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = Clue

PROJECTVERSION = 1.1
LANGUAGE = English

APPICON = Clue.tiff
LOCAL_RESOURCES = Help

GLOBAL_RESOURCES = Clue.nib ClueBoard.nib ClueHuman.nib ClueInfo.nib\
                   ClueMessages.nib ClueRules.nib ClueSetup.nib\
                   ball-room.tiff billiard-room.tiff board.tiff\
                   candlestick.tiff Clue.tiff conservatory.tiff\
                   die1.tiff die2.tiff die3.tiff die4.tiff die5.tiff\
                   die6.tiff dining-room.tiff green.tiff hall.tiff\
                   kitchen.tiff knife.tiff lead-pipe.tiff library.tiff\
                   lounge.tiff mustard.tiff peacock.tiff plum.tiff\
                   revolver.tiff rope.tiff scarlet.tiff study.tiff\
                   white.tiff wrench.tiff ClueRules.rtfd HISTORY.txt\
                   PACKAGE_NUMBER README RELEASE_NUMBER

HFILES = ClueAnnaLyzer.h ClueBeaGinner.h ClueBoard.h ClueBoardView.h\
         ClueButton.h ClueCardPicker.h ClueComputer.h ClueCondArray.h\
         ClueCoordArray.h ClueCyBorg.h ClueCyLent.h ClueDeeDucer.h\
         ClueDefs.h ClueHuman.h ClueInfo.h ClueLoadNib.h ClueMap.h\
         ClueMessages.h ClueMgr.h CluePlayer.h ClueRandyMizer.h\
         ClueRules.h ClueSetup.h ClueTrace.h ClueUpdateStack.h

OTHERLINKED = ClueAnnaLyzer.mm ClueBeaGinner.mm ClueBoard.mm\
              ClueBoardView.mm ClueButton.mm ClueCardPicker.cc\
              ClueComputer.mm ClueCondArray.cc ClueCoordArray.cc\
              ClueCyBorg.mm ClueCyLent.mm ClueDeeDucer.mm ClueDefs.cc\
              ClueHuman.mm ClueInfo.mm ClueLoadNib.mm ClueMap.cc\
              ClueMessages.mm ClueMgr.mm CluePlayer.mm ClueRandyMizer.mm\
              ClueRules.mm ClueSetup.mm ClueTrace.mm ClueUpdateStack.cc

MFILES = Clue_main.m

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble

OTHERLINKEDOFILES = ClueAnnaLyzer.o ClueBeaGinner.o ClueBoard.o\
                    ClueBoardView.o ClueButton.o ClueCardPicker.o\
                    ClueComputer.o ClueCondArray.o ClueCoordArray.o\
                    ClueCyBorg.o ClueCyLent.o ClueDeeDucer.o ClueDefs.o\
                    ClueHuman.o ClueInfo.o ClueLoadNib.o ClueMap.o\
                    ClueMessages.o ClueMgr.o CluePlayer.o\
                    ClueRandyMizer.o ClueRules.o ClueSetup.o\
                    ClueTrace.o ClueUpdateStack.o

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = app.make
INSTALLDIR = /Games
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app Clue.tiff

LIBS = -lMiscTableScroll -lMedia_s -lNeXT_s -lIndexing_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


HEADER_PATHS = -I/LocalDeveloper/Headers
LIBRARY_PATHS = -L/LocalDeveloper/Libraries
PB_CFLAGS = -Wwrite-strings -Werror


-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
